import{a as S,S as v,i as M}from"./assets/vendor-f144e563.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const q="https://pixabay.com/api/";async function p(e,t){return(await S(q,{params:{key:"43244566-bb96021fc186f0172f7edc4d3",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const u=document.querySelector(".gallery"),H=document.querySelector(".form"),h=document.querySelector(".search-input"),g=document.querySelector(".loader"),m=document.querySelector(".load-more-btn");f();let c="",n=1;const d=15,P=new v(".gallery a",{captionsData:"alt",captionDelay:250});H.addEventListener("submit",$);async function $(e){if(e.preventDefault(),c=h.value.trim(),n=1,u.innerHTML="",!c){l("The field can not be empty!");return}O(),b();try{const t=await p(c,n,d),s=t.totalHits;if(!t.hits.length){l("Sorry, there are no images matching your search query. Please try again!");return}y(t.hits),h.value="",C(),d*n>=s&&(E(),L())}catch(t){l("Failed to fetch images. Please try again later."),console.error("Error:",t)}finally{f()}}m.addEventListener("click",async()=>{try{n+=1;const e=await p(c,n,d),t=e.totalHits;y(e.hits),b(),d*n>=t&&(E(),L()),T()}catch(e){l(`Error fetching more images: ${e}`),console.error("Error fetching more images:",e)}finally{f()}});function y(e){u.insertAdjacentHTML("beforeend",x(e)),P.refresh()}function x(e){return e.map(({webformatURL:t,largeImageURL:s,tags:a,likes:r,views:o,comments:i,downloads:w})=>`
    <li class="card">
      <a href="${s}" class="link">
        <img src="${t}" alt="${a}">
        <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${r}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${o}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${i}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${w}</p></li>
        </ul>
      </a>
    </li>
  `).join("")}function L(){const e=document.createElement("p");e.classList.add("end-message"),e.textContent="We're sorry, but you've reached the end of search results.",u.insertAdjacentElement("afterend",e)}function b(){g.classList.remove("hidden")}function f(){g.classList.add("hidden")}function C(){m.style.display="block"}function E(){m.style.display="none"}function O(){const e=document.querySelector(".end-message");e&&e.remove()}function l(e){M.error({message:e,messageColor:"#fff",backgroundColor:"#ef4040",position:"bottomRight",messageSize:"14px",messageLineHeight:"100%",iconColor:"grey",title:"Error"})}function T(){const e=document.querySelector(".gallery a");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
